/*
 * Copyright ThinkTank Mathematics Limited 2007.
 * Copyright 2003-2007 Keith Seymour.
 * Copyright 1992-2007 The University of Tennessee. All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * 
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 * 
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer listed
 *   in this license in the documentation and/or other materials
 *   provided with the distribution.
 * 
 * - Neither the name of the copyright holders nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * This file was auto-generated by the org.netlib.generate.JavaGenerator
 * program, a part of F2J.
 * 
 * @see http://sourceforge.net/projects/f2j
 */

#include "f2j_jni.h"
#include "org_netlib_arpack_NativeARPACK.h"

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dmout (JNIEnv * env, jobject calling_obj, jint arg1, jint arg2, jint arg3, jdoubleArray arg4, jint arg6, jint arg7, jstring arg8){
	jdouble * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	char * jni_arg8 = (char *)(*env)->GetStringUTFChars(env, arg8, JNI_FALSE);

	dmout_(&arg1, &arg2, &arg3, jni_arg4, &arg6, &arg7, jni_arg8);

	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleaseStringUTFChars(env, arg8, jni_arg8);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dvout (JNIEnv * env, jobject calling_obj, jint arg1, jint arg2, jdoubleArray arg3, jint arg5, jstring arg6){
	jdouble * jni_arg3 = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	check_memory(env, jni_arg3);
	char * jni_arg6 = (char *)(*env)->GetStringUTFChars(env, arg6, JNI_FALSE);

	dvout_(&arg1, &arg2, jni_arg3, &arg5, jni_arg6);

	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3, 0);
	(*env)->ReleaseStringUTFChars(env, arg6, jni_arg6);
}

JNIEXPORT jint JNICALL Java_org_netlib_arpack_NativeARPACK_icnteq (JNIEnv * env, jobject calling_obj, jint arg1, jintArray arg2, jint arg4){
	jint * jni_arg2 = (*env)->GetPrimitiveArrayCritical(env, arg2, JNI_FALSE);
	check_memory(env, jni_arg2);
	jint returnValue;

	returnValue = icnteq_(&arg1, jni_arg2, &arg4);

	(*env)->ReleasePrimitiveArrayCritical(env, arg2, jni_arg2, 0);

	return returnValue;
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_icopy (JNIEnv * env, jobject calling_obj, jint arg1, jintArray arg2, jint arg4, jintArray arg5, jint arg7){
	jint * jni_arg2 = (*env)->GetPrimitiveArrayCritical(env, arg2, JNI_FALSE);
	check_memory(env, jni_arg2);
	jint * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);

	icopy_(&arg1, jni_arg2, &arg4, jni_arg5, &arg7);

	(*env)->ReleasePrimitiveArrayCritical(env, arg2, jni_arg2, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_iset (JNIEnv * env, jobject calling_obj, jint arg1, jint arg2, jintArray arg3, jint arg5){
	jint * jni_arg3 = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	check_memory(env, jni_arg3);

	iset_(&arg1, &arg2, jni_arg3, &arg5);

	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_iswap (JNIEnv * env, jobject calling_obj, jint arg1, jintArray arg2, jint arg4, jintArray arg5, jint arg7){
	jint * jni_arg2 = (*env)->GetPrimitiveArrayCritical(env, arg2, JNI_FALSE);
	check_memory(env, jni_arg2);
	jint * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);

	iswap_(&arg1, jni_arg2, &arg4, jni_arg5, &arg7);

	(*env)->ReleasePrimitiveArrayCritical(env, arg2, jni_arg2, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_ivout (JNIEnv * env, jobject calling_obj, jint arg1, jint arg2, jintArray arg3, jint arg5, jstring arg6){
	jint * jni_arg3 = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	check_memory(env, jni_arg3);
	char * jni_arg6 = (char *)(*env)->GetStringUTFChars(env, arg6, JNI_FALSE);

	ivout_(&arg1, &arg2, jni_arg3, &arg5, jni_arg6);

	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3, 0);
	(*env)->ReleaseStringUTFChars(env, arg6, jni_arg6);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_second (JNIEnv * env, jobject calling_obj, jobject arg1){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "D");
	jfloat jni_arg1 = (*env)->GetFloatField(env, arg1, jni_arg1Id);

	second_(&jni_arg1);

	(*env)->SetFloatField(env, arg1, jni_arg1Id, jni_arg1);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_smout (JNIEnv * env, jobject calling_obj, jint arg1, jint arg2, jint arg3, jfloatArray arg4, jint arg6, jint arg7, jstring arg8){
	jfloat * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	char * jni_arg8 = (char *)(*env)->GetStringUTFChars(env, arg8, JNI_FALSE);

	smout_(&arg1, &arg2, &arg3, jni_arg4, &arg6, &arg7, jni_arg8);

	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleaseStringUTFChars(env, arg8, jni_arg8);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_svout (JNIEnv * env, jobject calling_obj, jint arg1, jint arg2, jfloatArray arg3, jint arg5, jstring arg6){
	jfloat * jni_arg3 = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	check_memory(env, jni_arg3);
	char * jni_arg6 = (char *)(*env)->GetStringUTFChars(env, arg6, JNI_FALSE);

	svout_(&arg1, &arg2, jni_arg3, &arg5, jni_arg6);

	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3, 0);
	(*env)->ReleaseStringUTFChars(env, arg6, jni_arg6);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dgetv0 (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jboolean arg4, jint arg5, jint arg6, jdoubleArray arg7, jint arg9, jdoubleArray arg10, jobject arg12, jintArray arg13, jdoubleArray arg15, jobject arg17){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	logical jni_arg4 = (logical)arg4;
	jdouble * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jdouble * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jclass jni_arg12Class = (*env)->GetObjectClass(env, arg12);
	jfieldID jni_arg12Id = (*env)->GetFieldID(env, jni_arg12Class, "val", "D");
	jdouble jni_arg12 = (*env)->GetDoubleField(env, arg12, jni_arg12Id);
	jint * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);
	jdouble * jni_arg15 = (*env)->GetPrimitiveArrayCritical(env, arg15, JNI_FALSE);
	check_memory(env, jni_arg15);
	jclass jni_arg17Class = (*env)->GetObjectClass(env, arg17);
	jfieldID jni_arg17Id = (*env)->GetFieldID(env, jni_arg17Class, "val", "I");
	jint jni_arg17 = (*env)->GetIntField(env, arg17, jni_arg17Id);

	dgetv0_(&jni_arg1, jni_arg2, &arg3, &jni_arg4, &arg5, &arg6, jni_arg7, &arg9, jni_arg10, &jni_arg12, jni_arg13, jni_arg15, &jni_arg17);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->SetDoubleField(env, arg12, jni_arg12Id, jni_arg12);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg15, jni_arg15, 0);
	(*env)->SetIntField(env, arg17, jni_arg17Id, jni_arg17);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dlaqrb (JNIEnv * env, jobject calling_obj, jboolean arg1, jint arg2, jint arg3, jint arg4, jdoubleArray arg5, jint arg7, jdoubleArray arg8, jdoubleArray arg10, jdoubleArray arg12, jobject arg14){
	logical jni_arg1 = (logical)arg1;
	jdouble * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);
	jdouble * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jdouble * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jdouble * jni_arg12 = (*env)->GetPrimitiveArrayCritical(env, arg12, JNI_FALSE);
	check_memory(env, jni_arg12);
	jclass jni_arg14Class = (*env)->GetObjectClass(env, arg14);
	jfieldID jni_arg14Id = (*env)->GetFieldID(env, jni_arg14Class, "val", "I");
	jint jni_arg14 = (*env)->GetIntField(env, arg14, jni_arg14Id);

	dlaqrb_(&jni_arg1, &arg2, &arg3, &arg4, jni_arg5, &arg7, jni_arg8, jni_arg10, jni_arg12, &jni_arg14);

	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg12, jni_arg12, 0);
	(*env)->SetIntField(env, arg14, jni_arg14Id, jni_arg14);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dnaitr (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jint arg4, jint arg5, jint arg6, jdoubleArray arg7, jobject arg9, jdoubleArray arg10, jint arg12, jdoubleArray arg13, jint arg15, jintArray arg16, jdoubleArray arg18, jobject arg20){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jdouble * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jclass jni_arg9Class = (*env)->GetObjectClass(env, arg9);
	jfieldID jni_arg9Id = (*env)->GetFieldID(env, jni_arg9Class, "val", "D");
	jdouble jni_arg9 = (*env)->GetDoubleField(env, arg9, jni_arg9Id);
	jdouble * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jdouble * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);
	jint * jni_arg16 = (*env)->GetPrimitiveArrayCritical(env, arg16, JNI_FALSE);
	check_memory(env, jni_arg16);
	jdouble * jni_arg18 = (*env)->GetPrimitiveArrayCritical(env, arg18, JNI_FALSE);
	check_memory(env, jni_arg18);
	jclass jni_arg20Class = (*env)->GetObjectClass(env, arg20);
	jfieldID jni_arg20Id = (*env)->GetFieldID(env, jni_arg20Class, "val", "I");
	jint jni_arg20 = (*env)->GetIntField(env, arg20, jni_arg20Id);

	dnaitr_(&jni_arg1, jni_arg2, &arg3, &arg4, &arg5, &arg6, jni_arg7, &jni_arg9, jni_arg10, &arg12, jni_arg13, &arg15, jni_arg16, jni_arg18, &jni_arg20);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->SetDoubleField(env, arg9, jni_arg9Id, jni_arg9);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg16, jni_arg16, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg18, jni_arg18, 0);
	(*env)->SetIntField(env, arg20, jni_arg20Id, jni_arg20);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dnapps (JNIEnv * env, jobject calling_obj, jint arg1, jobject arg2, jint arg3, jdoubleArray arg4, jdoubleArray arg6, jdoubleArray arg8, jint arg10, jdoubleArray arg11, jint arg13, jdoubleArray arg14, jdoubleArray arg16, jint arg18, jdoubleArray arg19, jdoubleArray arg21){
	jclass jni_arg2Class = (*env)->GetObjectClass(env, arg2);
	jfieldID jni_arg2Id = (*env)->GetFieldID(env, jni_arg2Class, "val", "I");
	jint jni_arg2 = (*env)->GetIntField(env, arg2, jni_arg2Id);
	jdouble * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jdouble * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jdouble * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jdouble * jni_arg11 = (*env)->GetPrimitiveArrayCritical(env, arg11, JNI_FALSE);
	check_memory(env, jni_arg11);
	jdouble * jni_arg14 = (*env)->GetPrimitiveArrayCritical(env, arg14, JNI_FALSE);
	check_memory(env, jni_arg14);
	jdouble * jni_arg16 = (*env)->GetPrimitiveArrayCritical(env, arg16, JNI_FALSE);
	check_memory(env, jni_arg16);
	jdouble * jni_arg19 = (*env)->GetPrimitiveArrayCritical(env, arg19, JNI_FALSE);
	check_memory(env, jni_arg19);
	jdouble * jni_arg21 = (*env)->GetPrimitiveArrayCritical(env, arg21, JNI_FALSE);
	check_memory(env, jni_arg21);

	dnapps_(&arg1, &jni_arg2, &arg3, jni_arg4, jni_arg6, jni_arg8, &arg10, jni_arg11, &arg13, jni_arg14, jni_arg16, &arg18, jni_arg19, jni_arg21);

	(*env)->SetIntField(env, arg2, jni_arg2Id, jni_arg2);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg11, jni_arg11, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg14, jni_arg14, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg16, jni_arg16, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg19, jni_arg19, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg21, jni_arg21, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dnaup2 (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jstring arg4, jobject arg5, jobject arg6, jdouble arg7, jdoubleArray arg8, jint arg10, jint arg11, jint arg12, jobject arg13, jdoubleArray arg14, jint arg16, jdoubleArray arg17, jint arg19, jdoubleArray arg20, jdoubleArray arg22, jdoubleArray arg24, jdoubleArray arg26, jint arg28, jdoubleArray arg29, jintArray arg31, jdoubleArray arg33, jobject arg35){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	char * jni_arg4 = (char *)(*env)->GetStringUTFChars(env, arg4, JNI_FALSE);
	jclass jni_arg5Class = (*env)->GetObjectClass(env, arg5);
	jfieldID jni_arg5Id = (*env)->GetFieldID(env, jni_arg5Class, "val", "I");
	jint jni_arg5 = (*env)->GetIntField(env, arg5, jni_arg5Id);
	jclass jni_arg6Class = (*env)->GetObjectClass(env, arg6);
	jfieldID jni_arg6Id = (*env)->GetFieldID(env, jni_arg6Class, "val", "I");
	jint jni_arg6 = (*env)->GetIntField(env, arg6, jni_arg6Id);
	jdouble * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jclass jni_arg13Class = (*env)->GetObjectClass(env, arg13);
	jfieldID jni_arg13Id = (*env)->GetFieldID(env, jni_arg13Class, "val", "I");
	jint jni_arg13 = (*env)->GetIntField(env, arg13, jni_arg13Id);
	jdouble * jni_arg14 = (*env)->GetPrimitiveArrayCritical(env, arg14, JNI_FALSE);
	check_memory(env, jni_arg14);
	jdouble * jni_arg17 = (*env)->GetPrimitiveArrayCritical(env, arg17, JNI_FALSE);
	check_memory(env, jni_arg17);
	jdouble * jni_arg20 = (*env)->GetPrimitiveArrayCritical(env, arg20, JNI_FALSE);
	check_memory(env, jni_arg20);
	jdouble * jni_arg22 = (*env)->GetPrimitiveArrayCritical(env, arg22, JNI_FALSE);
	check_memory(env, jni_arg22);
	jdouble * jni_arg24 = (*env)->GetPrimitiveArrayCritical(env, arg24, JNI_FALSE);
	check_memory(env, jni_arg24);
	jdouble * jni_arg26 = (*env)->GetPrimitiveArrayCritical(env, arg26, JNI_FALSE);
	check_memory(env, jni_arg26);
	jdouble * jni_arg29 = (*env)->GetPrimitiveArrayCritical(env, arg29, JNI_FALSE);
	check_memory(env, jni_arg29);
	jint * jni_arg31 = (*env)->GetPrimitiveArrayCritical(env, arg31, JNI_FALSE);
	check_memory(env, jni_arg31);
	jdouble * jni_arg33 = (*env)->GetPrimitiveArrayCritical(env, arg33, JNI_FALSE);
	check_memory(env, jni_arg33);
	jclass jni_arg35Class = (*env)->GetObjectClass(env, arg35);
	jfieldID jni_arg35Id = (*env)->GetFieldID(env, jni_arg35Class, "val", "I");
	jint jni_arg35 = (*env)->GetIntField(env, arg35, jni_arg35Id);

	dnaup2_(&jni_arg1, jni_arg2, &arg3, jni_arg4, &jni_arg5, &jni_arg6, &arg7, jni_arg8, &arg10, &arg11, &arg12, &jni_arg13, jni_arg14, &arg16, jni_arg17, &arg19, jni_arg20, jni_arg22, jni_arg24, jni_arg26, &arg28, jni_arg29, jni_arg31, jni_arg33, &jni_arg35);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleaseStringUTFChars(env, arg4, jni_arg4);
	(*env)->SetIntField(env, arg5, jni_arg5Id, jni_arg5);
	(*env)->SetIntField(env, arg6, jni_arg6Id, jni_arg6);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->SetIntField(env, arg13, jni_arg13Id, jni_arg13);
	(*env)->ReleasePrimitiveArrayCritical(env, arg14, jni_arg14, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg17, jni_arg17, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg20, jni_arg20, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg22, jni_arg22, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg24, jni_arg24, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg26, jni_arg26, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg29, jni_arg29, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg31, jni_arg31, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg33, jni_arg33, 0);
	(*env)->SetIntField(env, arg35, jni_arg35Id, jni_arg35);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dnaupd (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jstring arg4, jint arg5, jobject arg6, jdoubleArray arg7, jint arg9, jdoubleArray arg10, jint arg12, jintArray arg13, jintArray arg15, jdoubleArray arg17, jdoubleArray arg19, jint arg21, jobject arg22){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	char * jni_arg4 = (char *)(*env)->GetStringUTFChars(env, arg4, JNI_FALSE);
	jclass jni_arg6Class = (*env)->GetObjectClass(env, arg6);
	jfieldID jni_arg6Id = (*env)->GetFieldID(env, jni_arg6Class, "val", "D");
	jdouble jni_arg6 = (*env)->GetDoubleField(env, arg6, jni_arg6Id);
	jdouble * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jdouble * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jint * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);
	jint * jni_arg15 = (*env)->GetPrimitiveArrayCritical(env, arg15, JNI_FALSE);
	check_memory(env, jni_arg15);
	jdouble * jni_arg17 = (*env)->GetPrimitiveArrayCritical(env, arg17, JNI_FALSE);
	check_memory(env, jni_arg17);
	jdouble * jni_arg19 = (*env)->GetPrimitiveArrayCritical(env, arg19, JNI_FALSE);
	check_memory(env, jni_arg19);
	jclass jni_arg22Class = (*env)->GetObjectClass(env, arg22);
	jfieldID jni_arg22Id = (*env)->GetFieldID(env, jni_arg22Class, "val", "I");
	jint jni_arg22 = (*env)->GetIntField(env, arg22, jni_arg22Id);

	dnaupd_(&jni_arg1, jni_arg2, &arg3, jni_arg4, &arg5, &jni_arg6, jni_arg7, &arg9, jni_arg10, &arg12, jni_arg13, jni_arg15, jni_arg17, jni_arg19, &arg21, &jni_arg22);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleaseStringUTFChars(env, arg4, jni_arg4);
	(*env)->SetDoubleField(env, arg6, jni_arg6Id, jni_arg6);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg15, jni_arg15, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg17, jni_arg17, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg19, jni_arg19, 0);
	(*env)->SetIntField(env, arg22, jni_arg22Id, jni_arg22);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dnconv (JNIEnv * env, jobject calling_obj, jint arg1, jdoubleArray arg2, jdoubleArray arg4, jdoubleArray arg6, jdouble arg8, jobject arg9){
	jdouble * jni_arg2 = (*env)->GetPrimitiveArrayCritical(env, arg2, JNI_FALSE);
	check_memory(env, jni_arg2);
	jdouble * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jdouble * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jclass jni_arg9Class = (*env)->GetObjectClass(env, arg9);
	jfieldID jni_arg9Id = (*env)->GetFieldID(env, jni_arg9Class, "val", "I");
	jint jni_arg9 = (*env)->GetIntField(env, arg9, jni_arg9Id);

	dnconv_(&arg1, jni_arg2, jni_arg4, jni_arg6, &arg8, &jni_arg9);

	(*env)->ReleasePrimitiveArrayCritical(env, arg2, jni_arg2, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->SetIntField(env, arg9, jni_arg9Id, jni_arg9);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dneigh (JNIEnv * env, jobject calling_obj, jdouble arg1, jobject arg2, jdoubleArray arg3, jint arg5, jdoubleArray arg6, jdoubleArray arg8, jdoubleArray arg10, jdoubleArray arg12, jint arg14, jdoubleArray arg15, jobject arg17){
	jclass jni_arg2Class = (*env)->GetObjectClass(env, arg2);
	jfieldID jni_arg2Id = (*env)->GetFieldID(env, jni_arg2Class, "val", "I");
	jint jni_arg2 = (*env)->GetIntField(env, arg2, jni_arg2Id);
	jdouble * jni_arg3 = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	check_memory(env, jni_arg3);
	jdouble * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jdouble * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jdouble * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jdouble * jni_arg12 = (*env)->GetPrimitiveArrayCritical(env, arg12, JNI_FALSE);
	check_memory(env, jni_arg12);
	jdouble * jni_arg15 = (*env)->GetPrimitiveArrayCritical(env, arg15, JNI_FALSE);
	check_memory(env, jni_arg15);
	jclass jni_arg17Class = (*env)->GetObjectClass(env, arg17);
	jfieldID jni_arg17Id = (*env)->GetFieldID(env, jni_arg17Class, "val", "I");
	jint jni_arg17 = (*env)->GetIntField(env, arg17, jni_arg17Id);

	dneigh_(&arg1, &jni_arg2, jni_arg3, &arg5, jni_arg6, jni_arg8, jni_arg10, jni_arg12, &arg14, jni_arg15, &jni_arg17);

	(*env)->SetIntField(env, arg2, jni_arg2Id, jni_arg2);
	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg12, jni_arg12, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg15, jni_arg15, 0);
	(*env)->SetIntField(env, arg17, jni_arg17Id, jni_arg17);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dneupd (JNIEnv * env, jobject calling_obj, jboolean arg1, jstring arg2, jbooleanArray arg3, jdoubleArray arg5, jdoubleArray arg7, jdoubleArray arg9, jint arg11, jdouble arg12, jdouble arg13, jdoubleArray arg14, jstring arg16, jint arg17, jstring arg18, jobject arg19, jdouble arg20, jdoubleArray arg21, jint arg23, jdoubleArray arg24, jint arg26, jintArray arg27, jintArray arg29, jdoubleArray arg31, jdoubleArray arg33, jint arg35, jobject arg36){
	logical jni_arg1 = (logical)arg1;
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jboolean * jni_arg3Tmp = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	jint jni_arg3Size = (*env)->GetArrayLength(env, arg3);
	logical jni_arg3[jni_arg3Size];
	int jni_arg3i;
	jdouble * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);
	jdouble * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jdouble * jni_arg9 = (*env)->GetPrimitiveArrayCritical(env, arg9, JNI_FALSE);
	check_memory(env, jni_arg9);
	jdouble * jni_arg14 = (*env)->GetPrimitiveArrayCritical(env, arg14, JNI_FALSE);
	check_memory(env, jni_arg14);
	char * jni_arg16 = (char *)(*env)->GetStringUTFChars(env, arg16, JNI_FALSE);
	char * jni_arg18 = (char *)(*env)->GetStringUTFChars(env, arg18, JNI_FALSE);
	jclass jni_arg19Class = (*env)->GetObjectClass(env, arg19);
	jfieldID jni_arg19Id = (*env)->GetFieldID(env, jni_arg19Class, "val", "I");
	jint jni_arg19 = (*env)->GetIntField(env, arg19, jni_arg19Id);
	jdouble * jni_arg21 = (*env)->GetPrimitiveArrayCritical(env, arg21, JNI_FALSE);
	check_memory(env, jni_arg21);
	jdouble * jni_arg24 = (*env)->GetPrimitiveArrayCritical(env, arg24, JNI_FALSE);
	check_memory(env, jni_arg24);
	jint * jni_arg27 = (*env)->GetPrimitiveArrayCritical(env, arg27, JNI_FALSE);
	check_memory(env, jni_arg27);
	jint * jni_arg29 = (*env)->GetPrimitiveArrayCritical(env, arg29, JNI_FALSE);
	check_memory(env, jni_arg29);
	jdouble * jni_arg31 = (*env)->GetPrimitiveArrayCritical(env, arg31, JNI_FALSE);
	check_memory(env, jni_arg31);
	jdouble * jni_arg33 = (*env)->GetPrimitiveArrayCritical(env, arg33, JNI_FALSE);
	check_memory(env, jni_arg33);
	jclass jni_arg36Class = (*env)->GetObjectClass(env, arg36);
	jfieldID jni_arg36Id = (*env)->GetFieldID(env, jni_arg36Class, "val", "I");
	jint jni_arg36 = (*env)->GetIntField(env, arg36, jni_arg36Id);
	for (jni_arg3i = 0 ; jni_arg3i < jni_arg3Size ; jni_arg3i++){
		if (jni_arg3Tmp[jni_arg3i] == JNI_FALSE){
			jni_arg3[jni_arg3i] = 0;
		} else {
			jni_arg3[jni_arg3i] = 1;
		}
	}

	dneupd_(&jni_arg1, jni_arg2, jni_arg3, jni_arg5, jni_arg7, jni_arg9, &arg11, &arg12, &arg13, jni_arg14, jni_arg16, &arg17, jni_arg18, &jni_arg19, &arg20, jni_arg21, &arg23, jni_arg24, &arg26, jni_arg27, jni_arg29, jni_arg31, jni_arg33, &arg35, &jni_arg36);

	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	for (jni_arg3i = 0 ; jni_arg3i < jni_arg3Size ; jni_arg3i++){
		if (jni_arg3[jni_arg3i] == 0){
			jni_arg3Tmp[jni_arg3i] = JNI_FALSE;
		} else {
			jni_arg3Tmp[jni_arg3i] = JNI_TRUE;
		}
	}
	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3Tmp, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg9, jni_arg9, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg14, jni_arg14, 0);
	(*env)->ReleaseStringUTFChars(env, arg16, jni_arg16);
	(*env)->ReleaseStringUTFChars(env, arg18, jni_arg18);
	(*env)->SetIntField(env, arg19, jni_arg19Id, jni_arg19);
	(*env)->ReleasePrimitiveArrayCritical(env, arg21, jni_arg21, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg24, jni_arg24, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg27, jni_arg27, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg29, jni_arg29, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg31, jni_arg31, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg33, jni_arg33, 0);
	(*env)->SetIntField(env, arg36, jni_arg36Id, jni_arg36);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dngets (JNIEnv * env, jobject calling_obj, jint arg1, jstring arg2, jobject arg3, jobject arg4, jdoubleArray arg5, jdoubleArray arg7, jdoubleArray arg9, jdoubleArray arg11, jdoubleArray arg13){
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jclass jni_arg3Class = (*env)->GetObjectClass(env, arg3);
	jfieldID jni_arg3Id = (*env)->GetFieldID(env, jni_arg3Class, "val", "I");
	jint jni_arg3 = (*env)->GetIntField(env, arg3, jni_arg3Id);
	jclass jni_arg4Class = (*env)->GetObjectClass(env, arg4);
	jfieldID jni_arg4Id = (*env)->GetFieldID(env, jni_arg4Class, "val", "I");
	jint jni_arg4 = (*env)->GetIntField(env, arg4, jni_arg4Id);
	jdouble * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);
	jdouble * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jdouble * jni_arg9 = (*env)->GetPrimitiveArrayCritical(env, arg9, JNI_FALSE);
	check_memory(env, jni_arg9);
	jdouble * jni_arg11 = (*env)->GetPrimitiveArrayCritical(env, arg11, JNI_FALSE);
	check_memory(env, jni_arg11);
	jdouble * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);

	dngets_(&arg1, jni_arg2, &jni_arg3, &jni_arg4, jni_arg5, jni_arg7, jni_arg9, jni_arg11, jni_arg13);

	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->SetIntField(env, arg3, jni_arg3Id, jni_arg3);
	(*env)->SetIntField(env, arg4, jni_arg4Id, jni_arg4);
	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg9, jni_arg9, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg11, jni_arg11, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dsaitr (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jint arg4, jint arg5, jint arg6, jdoubleArray arg7, jobject arg9, jdoubleArray arg10, jint arg12, jdoubleArray arg13, jint arg15, jintArray arg16, jdoubleArray arg18, jobject arg20){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jdouble * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jclass jni_arg9Class = (*env)->GetObjectClass(env, arg9);
	jfieldID jni_arg9Id = (*env)->GetFieldID(env, jni_arg9Class, "val", "D");
	jdouble jni_arg9 = (*env)->GetDoubleField(env, arg9, jni_arg9Id);
	jdouble * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jdouble * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);
	jint * jni_arg16 = (*env)->GetPrimitiveArrayCritical(env, arg16, JNI_FALSE);
	check_memory(env, jni_arg16);
	jdouble * jni_arg18 = (*env)->GetPrimitiveArrayCritical(env, arg18, JNI_FALSE);
	check_memory(env, jni_arg18);
	jclass jni_arg20Class = (*env)->GetObjectClass(env, arg20);
	jfieldID jni_arg20Id = (*env)->GetFieldID(env, jni_arg20Class, "val", "I");
	jint jni_arg20 = (*env)->GetIntField(env, arg20, jni_arg20Id);

	dsaitr_(&jni_arg1, jni_arg2, &arg3, &arg4, &arg5, &arg6, jni_arg7, &jni_arg9, jni_arg10, &arg12, jni_arg13, &arg15, jni_arg16, jni_arg18, &jni_arg20);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->SetDoubleField(env, arg9, jni_arg9Id, jni_arg9);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg16, jni_arg16, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg18, jni_arg18, 0);
	(*env)->SetIntField(env, arg20, jni_arg20Id, jni_arg20);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dsapps (JNIEnv * env, jobject calling_obj, jint arg1, jint arg2, jint arg3, jdoubleArray arg4, jdoubleArray arg6, jint arg8, jdoubleArray arg9, jint arg11, jdoubleArray arg12, jdoubleArray arg14, jint arg16, jdoubleArray arg17){
	jdouble * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jdouble * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jdouble * jni_arg9 = (*env)->GetPrimitiveArrayCritical(env, arg9, JNI_FALSE);
	check_memory(env, jni_arg9);
	jdouble * jni_arg12 = (*env)->GetPrimitiveArrayCritical(env, arg12, JNI_FALSE);
	check_memory(env, jni_arg12);
	jdouble * jni_arg14 = (*env)->GetPrimitiveArrayCritical(env, arg14, JNI_FALSE);
	check_memory(env, jni_arg14);
	jdouble * jni_arg17 = (*env)->GetPrimitiveArrayCritical(env, arg17, JNI_FALSE);
	check_memory(env, jni_arg17);

	dsapps_(&arg1, &arg2, &arg3, jni_arg4, jni_arg6, &arg8, jni_arg9, &arg11, jni_arg12, jni_arg14, &arg16, jni_arg17);

	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg9, jni_arg9, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg12, jni_arg12, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg14, jni_arg14, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg17, jni_arg17, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dsaup2 (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jstring arg4, jobject arg5, jobject arg6, jdouble arg7, jdoubleArray arg8, jint arg10, jint arg11, jint arg12, jobject arg13, jdoubleArray arg14, jint arg16, jdoubleArray arg17, jint arg19, jdoubleArray arg20, jdoubleArray arg22, jdoubleArray arg24, jint arg26, jdoubleArray arg27, jintArray arg29, jdoubleArray arg31, jobject arg33){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	char * jni_arg4 = (char *)(*env)->GetStringUTFChars(env, arg4, JNI_FALSE);
	jclass jni_arg5Class = (*env)->GetObjectClass(env, arg5);
	jfieldID jni_arg5Id = (*env)->GetFieldID(env, jni_arg5Class, "val", "I");
	jint jni_arg5 = (*env)->GetIntField(env, arg5, jni_arg5Id);
	jclass jni_arg6Class = (*env)->GetObjectClass(env, arg6);
	jfieldID jni_arg6Id = (*env)->GetFieldID(env, jni_arg6Class, "val", "I");
	jint jni_arg6 = (*env)->GetIntField(env, arg6, jni_arg6Id);
	jdouble * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jclass jni_arg13Class = (*env)->GetObjectClass(env, arg13);
	jfieldID jni_arg13Id = (*env)->GetFieldID(env, jni_arg13Class, "val", "I");
	jint jni_arg13 = (*env)->GetIntField(env, arg13, jni_arg13Id);
	jdouble * jni_arg14 = (*env)->GetPrimitiveArrayCritical(env, arg14, JNI_FALSE);
	check_memory(env, jni_arg14);
	jdouble * jni_arg17 = (*env)->GetPrimitiveArrayCritical(env, arg17, JNI_FALSE);
	check_memory(env, jni_arg17);
	jdouble * jni_arg20 = (*env)->GetPrimitiveArrayCritical(env, arg20, JNI_FALSE);
	check_memory(env, jni_arg20);
	jdouble * jni_arg22 = (*env)->GetPrimitiveArrayCritical(env, arg22, JNI_FALSE);
	check_memory(env, jni_arg22);
	jdouble * jni_arg24 = (*env)->GetPrimitiveArrayCritical(env, arg24, JNI_FALSE);
	check_memory(env, jni_arg24);
	jdouble * jni_arg27 = (*env)->GetPrimitiveArrayCritical(env, arg27, JNI_FALSE);
	check_memory(env, jni_arg27);
	jint * jni_arg29 = (*env)->GetPrimitiveArrayCritical(env, arg29, JNI_FALSE);
	check_memory(env, jni_arg29);
	jdouble * jni_arg31 = (*env)->GetPrimitiveArrayCritical(env, arg31, JNI_FALSE);
	check_memory(env, jni_arg31);
	jclass jni_arg33Class = (*env)->GetObjectClass(env, arg33);
	jfieldID jni_arg33Id = (*env)->GetFieldID(env, jni_arg33Class, "val", "I");
	jint jni_arg33 = (*env)->GetIntField(env, arg33, jni_arg33Id);

	dsaup2_(&jni_arg1, jni_arg2, &arg3, jni_arg4, &jni_arg5, &jni_arg6, &arg7, jni_arg8, &arg10, &arg11, &arg12, &jni_arg13, jni_arg14, &arg16, jni_arg17, &arg19, jni_arg20, jni_arg22, jni_arg24, &arg26, jni_arg27, jni_arg29, jni_arg31, &jni_arg33);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleaseStringUTFChars(env, arg4, jni_arg4);
	(*env)->SetIntField(env, arg5, jni_arg5Id, jni_arg5);
	(*env)->SetIntField(env, arg6, jni_arg6Id, jni_arg6);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->SetIntField(env, arg13, jni_arg13Id, jni_arg13);
	(*env)->ReleasePrimitiveArrayCritical(env, arg14, jni_arg14, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg17, jni_arg17, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg20, jni_arg20, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg22, jni_arg22, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg24, jni_arg24, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg27, jni_arg27, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg29, jni_arg29, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg31, jni_arg31, 0);
	(*env)->SetIntField(env, arg33, jni_arg33Id, jni_arg33);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dsaupd (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jstring arg4, jint arg5, jobject arg6, jdoubleArray arg7, jint arg9, jdoubleArray arg10, jint arg12, jintArray arg13, jintArray arg15, jdoubleArray arg17, jdoubleArray arg19, jint arg21, jobject arg22){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	char * jni_arg4 = (char *)(*env)->GetStringUTFChars(env, arg4, JNI_FALSE);
	jclass jni_arg6Class = (*env)->GetObjectClass(env, arg6);
	jfieldID jni_arg6Id = (*env)->GetFieldID(env, jni_arg6Class, "val", "D");
	jdouble jni_arg6 = (*env)->GetDoubleField(env, arg6, jni_arg6Id);
	jdouble * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jdouble * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jint * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);
	jint * jni_arg15 = (*env)->GetPrimitiveArrayCritical(env, arg15, JNI_FALSE);
	check_memory(env, jni_arg15);
	jdouble * jni_arg17 = (*env)->GetPrimitiveArrayCritical(env, arg17, JNI_FALSE);
	check_memory(env, jni_arg17);
	jdouble * jni_arg19 = (*env)->GetPrimitiveArrayCritical(env, arg19, JNI_FALSE);
	check_memory(env, jni_arg19);
	jclass jni_arg22Class = (*env)->GetObjectClass(env, arg22);
	jfieldID jni_arg22Id = (*env)->GetFieldID(env, jni_arg22Class, "val", "I");
	jint jni_arg22 = (*env)->GetIntField(env, arg22, jni_arg22Id);

	dsaupd_(&jni_arg1, jni_arg2, &arg3, jni_arg4, &arg5, &jni_arg6, jni_arg7, &arg9, jni_arg10, &arg12, jni_arg13, jni_arg15, jni_arg17, jni_arg19, &arg21, &jni_arg22);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleaseStringUTFChars(env, arg4, jni_arg4);
	(*env)->SetDoubleField(env, arg6, jni_arg6Id, jni_arg6);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg15, jni_arg15, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg17, jni_arg17, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg19, jni_arg19, 0);
	(*env)->SetIntField(env, arg22, jni_arg22Id, jni_arg22);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dsconv (JNIEnv * env, jobject calling_obj, jint arg1, jdoubleArray arg2, jdoubleArray arg4, jdouble arg6, jobject arg7){
	jdouble * jni_arg2 = (*env)->GetPrimitiveArrayCritical(env, arg2, JNI_FALSE);
	check_memory(env, jni_arg2);
	jdouble * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jclass jni_arg7Class = (*env)->GetObjectClass(env, arg7);
	jfieldID jni_arg7Id = (*env)->GetFieldID(env, jni_arg7Class, "val", "I");
	jint jni_arg7 = (*env)->GetIntField(env, arg7, jni_arg7Id);

	dsconv_(&arg1, jni_arg2, jni_arg4, &arg6, &jni_arg7);

	(*env)->ReleasePrimitiveArrayCritical(env, arg2, jni_arg2, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->SetIntField(env, arg7, jni_arg7Id, jni_arg7);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dseigt (JNIEnv * env, jobject calling_obj, jdouble arg1, jint arg2, jdoubleArray arg3, jint arg5, jdoubleArray arg6, jdoubleArray arg8, jdoubleArray arg10, jobject arg12){
	jdouble * jni_arg3 = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	check_memory(env, jni_arg3);
	jdouble * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jdouble * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jdouble * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jclass jni_arg12Class = (*env)->GetObjectClass(env, arg12);
	jfieldID jni_arg12Id = (*env)->GetFieldID(env, jni_arg12Class, "val", "I");
	jint jni_arg12 = (*env)->GetIntField(env, arg12, jni_arg12Id);

	dseigt_(&arg1, &arg2, jni_arg3, &arg5, jni_arg6, jni_arg8, jni_arg10, &jni_arg12);

	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->SetIntField(env, arg12, jni_arg12Id, jni_arg12);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dsesrt (JNIEnv * env, jobject calling_obj, jstring arg1, jboolean arg2, jint arg3, jdoubleArray arg4, jint arg6, jdoubleArray arg7, jint arg9){
	char * jni_arg1 = (char *)(*env)->GetStringUTFChars(env, arg1, JNI_FALSE);
	logical jni_arg2 = (logical)arg2;
	jdouble * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jdouble * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);

	dsesrt_(jni_arg1, &jni_arg2, &arg3, jni_arg4, &arg6, jni_arg7, &arg9);

	(*env)->ReleaseStringUTFChars(env, arg1, jni_arg1);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dseupd (JNIEnv * env, jobject calling_obj, jboolean arg1, jstring arg2, jbooleanArray arg3, jdoubleArray arg5, jdoubleArray arg7, jint arg9, jdouble arg10, jstring arg11, jint arg12, jstring arg13, jobject arg14, jdouble arg15, jdoubleArray arg16, jint arg18, jdoubleArray arg19, jint arg21, jintArray arg22, jintArray arg24, jdoubleArray arg26, jdoubleArray arg28, jint arg30, jobject arg31){
	logical jni_arg1 = (logical)arg1;
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jboolean * jni_arg3Tmp = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	jint jni_arg3Size = (*env)->GetArrayLength(env, arg3);
	logical jni_arg3[jni_arg3Size];
	int jni_arg3i;
	jdouble * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);
	jdouble * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	char * jni_arg11 = (char *)(*env)->GetStringUTFChars(env, arg11, JNI_FALSE);
	char * jni_arg13 = (char *)(*env)->GetStringUTFChars(env, arg13, JNI_FALSE);
	jclass jni_arg14Class = (*env)->GetObjectClass(env, arg14);
	jfieldID jni_arg14Id = (*env)->GetFieldID(env, jni_arg14Class, "val", "I");
	jint jni_arg14 = (*env)->GetIntField(env, arg14, jni_arg14Id);
	jdouble * jni_arg16 = (*env)->GetPrimitiveArrayCritical(env, arg16, JNI_FALSE);
	check_memory(env, jni_arg16);
	jdouble * jni_arg19 = (*env)->GetPrimitiveArrayCritical(env, arg19, JNI_FALSE);
	check_memory(env, jni_arg19);
	jint * jni_arg22 = (*env)->GetPrimitiveArrayCritical(env, arg22, JNI_FALSE);
	check_memory(env, jni_arg22);
	jint * jni_arg24 = (*env)->GetPrimitiveArrayCritical(env, arg24, JNI_FALSE);
	check_memory(env, jni_arg24);
	jdouble * jni_arg26 = (*env)->GetPrimitiveArrayCritical(env, arg26, JNI_FALSE);
	check_memory(env, jni_arg26);
	jdouble * jni_arg28 = (*env)->GetPrimitiveArrayCritical(env, arg28, JNI_FALSE);
	check_memory(env, jni_arg28);
	jclass jni_arg31Class = (*env)->GetObjectClass(env, arg31);
	jfieldID jni_arg31Id = (*env)->GetFieldID(env, jni_arg31Class, "val", "I");
	jint jni_arg31 = (*env)->GetIntField(env, arg31, jni_arg31Id);
	for (jni_arg3i = 0 ; jni_arg3i < jni_arg3Size ; jni_arg3i++){
		if (jni_arg3Tmp[jni_arg3i] == JNI_FALSE){
			jni_arg3[jni_arg3i] = 0;
		} else {
			jni_arg3[jni_arg3i] = 1;
		}
	}

	dseupd_(&jni_arg1, jni_arg2, jni_arg3, jni_arg5, jni_arg7, &arg9, &arg10, jni_arg11, &arg12, jni_arg13, &jni_arg14, &arg15, jni_arg16, &arg18, jni_arg19, &arg21, jni_arg22, jni_arg24, jni_arg26, jni_arg28, &arg30, &jni_arg31);

	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	for (jni_arg3i = 0 ; jni_arg3i < jni_arg3Size ; jni_arg3i++){
		if (jni_arg3[jni_arg3i] == 0){
			jni_arg3Tmp[jni_arg3i] = JNI_FALSE;
		} else {
			jni_arg3Tmp[jni_arg3i] = JNI_TRUE;
		}
	}
	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3Tmp, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleaseStringUTFChars(env, arg11, jni_arg11);
	(*env)->ReleaseStringUTFChars(env, arg13, jni_arg13);
	(*env)->SetIntField(env, arg14, jni_arg14Id, jni_arg14);
	(*env)->ReleasePrimitiveArrayCritical(env, arg16, jni_arg16, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg19, jni_arg19, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg22, jni_arg22, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg24, jni_arg24, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg26, jni_arg26, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg28, jni_arg28, 0);
	(*env)->SetIntField(env, arg31, jni_arg31Id, jni_arg31);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dsgets (JNIEnv * env, jobject calling_obj, jint arg1, jstring arg2, jobject arg3, jobject arg4, jdoubleArray arg5, jdoubleArray arg7, jdoubleArray arg9){
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jclass jni_arg3Class = (*env)->GetObjectClass(env, arg3);
	jfieldID jni_arg3Id = (*env)->GetFieldID(env, jni_arg3Class, "val", "I");
	jint jni_arg3 = (*env)->GetIntField(env, arg3, jni_arg3Id);
	jclass jni_arg4Class = (*env)->GetObjectClass(env, arg4);
	jfieldID jni_arg4Id = (*env)->GetFieldID(env, jni_arg4Class, "val", "I");
	jint jni_arg4 = (*env)->GetIntField(env, arg4, jni_arg4Id);
	jdouble * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);
	jdouble * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jdouble * jni_arg9 = (*env)->GetPrimitiveArrayCritical(env, arg9, JNI_FALSE);
	check_memory(env, jni_arg9);

	dsgets_(&arg1, jni_arg2, &jni_arg3, &jni_arg4, jni_arg5, jni_arg7, jni_arg9);

	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->SetIntField(env, arg3, jni_arg3Id, jni_arg3);
	(*env)->SetIntField(env, arg4, jni_arg4Id, jni_arg4);
	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg9, jni_arg9, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dsortc (JNIEnv * env, jobject calling_obj, jstring arg1, jboolean arg2, jint arg3, jdoubleArray arg4, jdoubleArray arg6, jdoubleArray arg8){
	char * jni_arg1 = (char *)(*env)->GetStringUTFChars(env, arg1, JNI_FALSE);
	logical jni_arg2 = (logical)arg2;
	jdouble * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jdouble * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jdouble * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);

	dsortc_(jni_arg1, &jni_arg2, &arg3, jni_arg4, jni_arg6, jni_arg8);

	(*env)->ReleaseStringUTFChars(env, arg1, jni_arg1);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dsortr (JNIEnv * env, jobject calling_obj, jstring arg1, jboolean arg2, jint arg3, jdoubleArray arg4, jdoubleArray arg6){
	char * jni_arg1 = (char *)(*env)->GetStringUTFChars(env, arg1, JNI_FALSE);
	logical jni_arg2 = (logical)arg2;
	jdouble * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jdouble * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);

	dsortr_(jni_arg1, &jni_arg2, &arg3, jni_arg4, jni_arg6);

	(*env)->ReleaseStringUTFChars(env, arg1, jni_arg1);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dstatn (JNIEnv * env, jobject calling_obj){

	dstatn_();

}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dstats (JNIEnv * env, jobject calling_obj){

	dstats_();

}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_dstqrb (JNIEnv * env, jobject calling_obj, jint arg1, jdoubleArray arg2, jdoubleArray arg4, jdoubleArray arg6, jdoubleArray arg8, jobject arg10){
	jdouble * jni_arg2 = (*env)->GetPrimitiveArrayCritical(env, arg2, JNI_FALSE);
	check_memory(env, jni_arg2);
	jdouble * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jdouble * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jdouble * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jclass jni_arg10Class = (*env)->GetObjectClass(env, arg10);
	jfieldID jni_arg10Id = (*env)->GetFieldID(env, jni_arg10Class, "val", "I");
	jint jni_arg10 = (*env)->GetIntField(env, arg10, jni_arg10Id);

	dstqrb_(&arg1, jni_arg2, jni_arg4, jni_arg6, jni_arg8, &jni_arg10);

	(*env)->ReleasePrimitiveArrayCritical(env, arg2, jni_arg2, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->SetIntField(env, arg10, jni_arg10Id, jni_arg10);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_sgetv0 (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jboolean arg4, jint arg5, jint arg6, jfloatArray arg7, jint arg9, jfloatArray arg10, jobject arg12, jintArray arg13, jfloatArray arg15, jobject arg17){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	logical jni_arg4 = (logical)arg4;
	jfloat * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jfloat * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jclass jni_arg12Class = (*env)->GetObjectClass(env, arg12);
	jfieldID jni_arg12Id = (*env)->GetFieldID(env, jni_arg12Class, "val", "D");
	jfloat jni_arg12 = (*env)->GetFloatField(env, arg12, jni_arg12Id);
	jint * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);
	jfloat * jni_arg15 = (*env)->GetPrimitiveArrayCritical(env, arg15, JNI_FALSE);
	check_memory(env, jni_arg15);
	jclass jni_arg17Class = (*env)->GetObjectClass(env, arg17);
	jfieldID jni_arg17Id = (*env)->GetFieldID(env, jni_arg17Class, "val", "I");
	jint jni_arg17 = (*env)->GetIntField(env, arg17, jni_arg17Id);

	sgetv0_(&jni_arg1, jni_arg2, &arg3, &jni_arg4, &arg5, &arg6, jni_arg7, &arg9, jni_arg10, &jni_arg12, jni_arg13, jni_arg15, &jni_arg17);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->SetFloatField(env, arg12, jni_arg12Id, jni_arg12);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg15, jni_arg15, 0);
	(*env)->SetIntField(env, arg17, jni_arg17Id, jni_arg17);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_slaqrb (JNIEnv * env, jobject calling_obj, jboolean arg1, jint arg2, jint arg3, jint arg4, jfloatArray arg5, jint arg7, jfloatArray arg8, jfloatArray arg10, jfloatArray arg12, jobject arg14){
	logical jni_arg1 = (logical)arg1;
	jfloat * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);
	jfloat * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jfloat * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jfloat * jni_arg12 = (*env)->GetPrimitiveArrayCritical(env, arg12, JNI_FALSE);
	check_memory(env, jni_arg12);
	jclass jni_arg14Class = (*env)->GetObjectClass(env, arg14);
	jfieldID jni_arg14Id = (*env)->GetFieldID(env, jni_arg14Class, "val", "I");
	jint jni_arg14 = (*env)->GetIntField(env, arg14, jni_arg14Id);

	slaqrb_(&jni_arg1, &arg2, &arg3, &arg4, jni_arg5, &arg7, jni_arg8, jni_arg10, jni_arg12, &jni_arg14);

	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg12, jni_arg12, 0);
	(*env)->SetIntField(env, arg14, jni_arg14Id, jni_arg14);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_snaitr (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jint arg4, jint arg5, jint arg6, jfloatArray arg7, jobject arg9, jfloatArray arg10, jint arg12, jfloatArray arg13, jint arg15, jintArray arg16, jfloatArray arg18, jobject arg20){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jfloat * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jclass jni_arg9Class = (*env)->GetObjectClass(env, arg9);
	jfieldID jni_arg9Id = (*env)->GetFieldID(env, jni_arg9Class, "val", "D");
	jfloat jni_arg9 = (*env)->GetFloatField(env, arg9, jni_arg9Id);
	jfloat * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jfloat * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);
	jint * jni_arg16 = (*env)->GetPrimitiveArrayCritical(env, arg16, JNI_FALSE);
	check_memory(env, jni_arg16);
	jfloat * jni_arg18 = (*env)->GetPrimitiveArrayCritical(env, arg18, JNI_FALSE);
	check_memory(env, jni_arg18);
	jclass jni_arg20Class = (*env)->GetObjectClass(env, arg20);
	jfieldID jni_arg20Id = (*env)->GetFieldID(env, jni_arg20Class, "val", "I");
	jint jni_arg20 = (*env)->GetIntField(env, arg20, jni_arg20Id);

	snaitr_(&jni_arg1, jni_arg2, &arg3, &arg4, &arg5, &arg6, jni_arg7, &jni_arg9, jni_arg10, &arg12, jni_arg13, &arg15, jni_arg16, jni_arg18, &jni_arg20);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->SetFloatField(env, arg9, jni_arg9Id, jni_arg9);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg16, jni_arg16, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg18, jni_arg18, 0);
	(*env)->SetIntField(env, arg20, jni_arg20Id, jni_arg20);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_snapps (JNIEnv * env, jobject calling_obj, jint arg1, jobject arg2, jint arg3, jfloatArray arg4, jfloatArray arg6, jfloatArray arg8, jint arg10, jfloatArray arg11, jint arg13, jfloatArray arg14, jfloatArray arg16, jint arg18, jfloatArray arg19, jfloatArray arg21){
	jclass jni_arg2Class = (*env)->GetObjectClass(env, arg2);
	jfieldID jni_arg2Id = (*env)->GetFieldID(env, jni_arg2Class, "val", "I");
	jint jni_arg2 = (*env)->GetIntField(env, arg2, jni_arg2Id);
	jfloat * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jfloat * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jfloat * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jfloat * jni_arg11 = (*env)->GetPrimitiveArrayCritical(env, arg11, JNI_FALSE);
	check_memory(env, jni_arg11);
	jfloat * jni_arg14 = (*env)->GetPrimitiveArrayCritical(env, arg14, JNI_FALSE);
	check_memory(env, jni_arg14);
	jfloat * jni_arg16 = (*env)->GetPrimitiveArrayCritical(env, arg16, JNI_FALSE);
	check_memory(env, jni_arg16);
	jfloat * jni_arg19 = (*env)->GetPrimitiveArrayCritical(env, arg19, JNI_FALSE);
	check_memory(env, jni_arg19);
	jfloat * jni_arg21 = (*env)->GetPrimitiveArrayCritical(env, arg21, JNI_FALSE);
	check_memory(env, jni_arg21);

	snapps_(&arg1, &jni_arg2, &arg3, jni_arg4, jni_arg6, jni_arg8, &arg10, jni_arg11, &arg13, jni_arg14, jni_arg16, &arg18, jni_arg19, jni_arg21);

	(*env)->SetIntField(env, arg2, jni_arg2Id, jni_arg2);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg11, jni_arg11, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg14, jni_arg14, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg16, jni_arg16, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg19, jni_arg19, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg21, jni_arg21, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_snaup2 (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jstring arg4, jobject arg5, jobject arg6, jfloat arg7, jfloatArray arg8, jint arg10, jint arg11, jint arg12, jobject arg13, jfloatArray arg14, jint arg16, jfloatArray arg17, jint arg19, jfloatArray arg20, jfloatArray arg22, jfloatArray arg24, jfloatArray arg26, jint arg28, jfloatArray arg29, jintArray arg31, jfloatArray arg33, jobject arg35){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	char * jni_arg4 = (char *)(*env)->GetStringUTFChars(env, arg4, JNI_FALSE);
	jclass jni_arg5Class = (*env)->GetObjectClass(env, arg5);
	jfieldID jni_arg5Id = (*env)->GetFieldID(env, jni_arg5Class, "val", "I");
	jint jni_arg5 = (*env)->GetIntField(env, arg5, jni_arg5Id);
	jclass jni_arg6Class = (*env)->GetObjectClass(env, arg6);
	jfieldID jni_arg6Id = (*env)->GetFieldID(env, jni_arg6Class, "val", "I");
	jint jni_arg6 = (*env)->GetIntField(env, arg6, jni_arg6Id);
	jfloat * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jclass jni_arg13Class = (*env)->GetObjectClass(env, arg13);
	jfieldID jni_arg13Id = (*env)->GetFieldID(env, jni_arg13Class, "val", "I");
	jint jni_arg13 = (*env)->GetIntField(env, arg13, jni_arg13Id);
	jfloat * jni_arg14 = (*env)->GetPrimitiveArrayCritical(env, arg14, JNI_FALSE);
	check_memory(env, jni_arg14);
	jfloat * jni_arg17 = (*env)->GetPrimitiveArrayCritical(env, arg17, JNI_FALSE);
	check_memory(env, jni_arg17);
	jfloat * jni_arg20 = (*env)->GetPrimitiveArrayCritical(env, arg20, JNI_FALSE);
	check_memory(env, jni_arg20);
	jfloat * jni_arg22 = (*env)->GetPrimitiveArrayCritical(env, arg22, JNI_FALSE);
	check_memory(env, jni_arg22);
	jfloat * jni_arg24 = (*env)->GetPrimitiveArrayCritical(env, arg24, JNI_FALSE);
	check_memory(env, jni_arg24);
	jfloat * jni_arg26 = (*env)->GetPrimitiveArrayCritical(env, arg26, JNI_FALSE);
	check_memory(env, jni_arg26);
	jfloat * jni_arg29 = (*env)->GetPrimitiveArrayCritical(env, arg29, JNI_FALSE);
	check_memory(env, jni_arg29);
	jint * jni_arg31 = (*env)->GetPrimitiveArrayCritical(env, arg31, JNI_FALSE);
	check_memory(env, jni_arg31);
	jfloat * jni_arg33 = (*env)->GetPrimitiveArrayCritical(env, arg33, JNI_FALSE);
	check_memory(env, jni_arg33);
	jclass jni_arg35Class = (*env)->GetObjectClass(env, arg35);
	jfieldID jni_arg35Id = (*env)->GetFieldID(env, jni_arg35Class, "val", "I");
	jint jni_arg35 = (*env)->GetIntField(env, arg35, jni_arg35Id);

	snaup2_(&jni_arg1, jni_arg2, &arg3, jni_arg4, &jni_arg5, &jni_arg6, &arg7, jni_arg8, &arg10, &arg11, &arg12, &jni_arg13, jni_arg14, &arg16, jni_arg17, &arg19, jni_arg20, jni_arg22, jni_arg24, jni_arg26, &arg28, jni_arg29, jni_arg31, jni_arg33, &jni_arg35);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleaseStringUTFChars(env, arg4, jni_arg4);
	(*env)->SetIntField(env, arg5, jni_arg5Id, jni_arg5);
	(*env)->SetIntField(env, arg6, jni_arg6Id, jni_arg6);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->SetIntField(env, arg13, jni_arg13Id, jni_arg13);
	(*env)->ReleasePrimitiveArrayCritical(env, arg14, jni_arg14, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg17, jni_arg17, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg20, jni_arg20, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg22, jni_arg22, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg24, jni_arg24, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg26, jni_arg26, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg29, jni_arg29, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg31, jni_arg31, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg33, jni_arg33, 0);
	(*env)->SetIntField(env, arg35, jni_arg35Id, jni_arg35);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_snaupd (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jstring arg4, jint arg5, jobject arg6, jfloatArray arg7, jint arg9, jfloatArray arg10, jint arg12, jintArray arg13, jintArray arg15, jfloatArray arg17, jfloatArray arg19, jint arg21, jobject arg22){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	char * jni_arg4 = (char *)(*env)->GetStringUTFChars(env, arg4, JNI_FALSE);
	jclass jni_arg6Class = (*env)->GetObjectClass(env, arg6);
	jfieldID jni_arg6Id = (*env)->GetFieldID(env, jni_arg6Class, "val", "D");
	jfloat jni_arg6 = (*env)->GetFloatField(env, arg6, jni_arg6Id);
	jfloat * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jfloat * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jint * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);
	jint * jni_arg15 = (*env)->GetPrimitiveArrayCritical(env, arg15, JNI_FALSE);
	check_memory(env, jni_arg15);
	jfloat * jni_arg17 = (*env)->GetPrimitiveArrayCritical(env, arg17, JNI_FALSE);
	check_memory(env, jni_arg17);
	jfloat * jni_arg19 = (*env)->GetPrimitiveArrayCritical(env, arg19, JNI_FALSE);
	check_memory(env, jni_arg19);
	jclass jni_arg22Class = (*env)->GetObjectClass(env, arg22);
	jfieldID jni_arg22Id = (*env)->GetFieldID(env, jni_arg22Class, "val", "I");
	jint jni_arg22 = (*env)->GetIntField(env, arg22, jni_arg22Id);

	snaupd_(&jni_arg1, jni_arg2, &arg3, jni_arg4, &arg5, &jni_arg6, jni_arg7, &arg9, jni_arg10, &arg12, jni_arg13, jni_arg15, jni_arg17, jni_arg19, &arg21, &jni_arg22);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleaseStringUTFChars(env, arg4, jni_arg4);
	(*env)->SetFloatField(env, arg6, jni_arg6Id, jni_arg6);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg15, jni_arg15, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg17, jni_arg17, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg19, jni_arg19, 0);
	(*env)->SetIntField(env, arg22, jni_arg22Id, jni_arg22);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_snconv (JNIEnv * env, jobject calling_obj, jint arg1, jfloatArray arg2, jfloatArray arg4, jfloatArray arg6, jfloat arg8, jobject arg9){
	jfloat * jni_arg2 = (*env)->GetPrimitiveArrayCritical(env, arg2, JNI_FALSE);
	check_memory(env, jni_arg2);
	jfloat * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jfloat * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jclass jni_arg9Class = (*env)->GetObjectClass(env, arg9);
	jfieldID jni_arg9Id = (*env)->GetFieldID(env, jni_arg9Class, "val", "I");
	jint jni_arg9 = (*env)->GetIntField(env, arg9, jni_arg9Id);

	snconv_(&arg1, jni_arg2, jni_arg4, jni_arg6, &arg8, &jni_arg9);

	(*env)->ReleasePrimitiveArrayCritical(env, arg2, jni_arg2, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->SetIntField(env, arg9, jni_arg9Id, jni_arg9);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_sneigh (JNIEnv * env, jobject calling_obj, jfloat arg1, jobject arg2, jfloatArray arg3, jint arg5, jfloatArray arg6, jfloatArray arg8, jfloatArray arg10, jfloatArray arg12, jint arg14, jfloatArray arg15, jobject arg17){
	jclass jni_arg2Class = (*env)->GetObjectClass(env, arg2);
	jfieldID jni_arg2Id = (*env)->GetFieldID(env, jni_arg2Class, "val", "I");
	jint jni_arg2 = (*env)->GetIntField(env, arg2, jni_arg2Id);
	jfloat * jni_arg3 = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	check_memory(env, jni_arg3);
	jfloat * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jfloat * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jfloat * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jfloat * jni_arg12 = (*env)->GetPrimitiveArrayCritical(env, arg12, JNI_FALSE);
	check_memory(env, jni_arg12);
	jfloat * jni_arg15 = (*env)->GetPrimitiveArrayCritical(env, arg15, JNI_FALSE);
	check_memory(env, jni_arg15);
	jclass jni_arg17Class = (*env)->GetObjectClass(env, arg17);
	jfieldID jni_arg17Id = (*env)->GetFieldID(env, jni_arg17Class, "val", "I");
	jint jni_arg17 = (*env)->GetIntField(env, arg17, jni_arg17Id);

	sneigh_(&arg1, &jni_arg2, jni_arg3, &arg5, jni_arg6, jni_arg8, jni_arg10, jni_arg12, &arg14, jni_arg15, &jni_arg17);

	(*env)->SetIntField(env, arg2, jni_arg2Id, jni_arg2);
	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg12, jni_arg12, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg15, jni_arg15, 0);
	(*env)->SetIntField(env, arg17, jni_arg17Id, jni_arg17);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_sneupd (JNIEnv * env, jobject calling_obj, jboolean arg1, jstring arg2, jbooleanArray arg3, jfloatArray arg5, jfloatArray arg7, jfloatArray arg9, jint arg11, jfloat arg12, jfloat arg13, jfloatArray arg14, jstring arg16, jint arg17, jstring arg18, jobject arg19, jfloat arg20, jfloatArray arg21, jint arg23, jfloatArray arg24, jint arg26, jintArray arg27, jintArray arg29, jfloatArray arg31, jfloatArray arg33, jint arg35, jobject arg36){
	logical jni_arg1 = (logical)arg1;
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jboolean * jni_arg3Tmp = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	jint jni_arg3Size = (*env)->GetArrayLength(env, arg3);
	logical jni_arg3[jni_arg3Size];
	int jni_arg3i;
	jfloat * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);
	jfloat * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jfloat * jni_arg9 = (*env)->GetPrimitiveArrayCritical(env, arg9, JNI_FALSE);
	check_memory(env, jni_arg9);
	jfloat * jni_arg14 = (*env)->GetPrimitiveArrayCritical(env, arg14, JNI_FALSE);
	check_memory(env, jni_arg14);
	char * jni_arg16 = (char *)(*env)->GetStringUTFChars(env, arg16, JNI_FALSE);
	char * jni_arg18 = (char *)(*env)->GetStringUTFChars(env, arg18, JNI_FALSE);
	jclass jni_arg19Class = (*env)->GetObjectClass(env, arg19);
	jfieldID jni_arg19Id = (*env)->GetFieldID(env, jni_arg19Class, "val", "I");
	jint jni_arg19 = (*env)->GetIntField(env, arg19, jni_arg19Id);
	jfloat * jni_arg21 = (*env)->GetPrimitiveArrayCritical(env, arg21, JNI_FALSE);
	check_memory(env, jni_arg21);
	jfloat * jni_arg24 = (*env)->GetPrimitiveArrayCritical(env, arg24, JNI_FALSE);
	check_memory(env, jni_arg24);
	jint * jni_arg27 = (*env)->GetPrimitiveArrayCritical(env, arg27, JNI_FALSE);
	check_memory(env, jni_arg27);
	jint * jni_arg29 = (*env)->GetPrimitiveArrayCritical(env, arg29, JNI_FALSE);
	check_memory(env, jni_arg29);
	jfloat * jni_arg31 = (*env)->GetPrimitiveArrayCritical(env, arg31, JNI_FALSE);
	check_memory(env, jni_arg31);
	jfloat * jni_arg33 = (*env)->GetPrimitiveArrayCritical(env, arg33, JNI_FALSE);
	check_memory(env, jni_arg33);
	jclass jni_arg36Class = (*env)->GetObjectClass(env, arg36);
	jfieldID jni_arg36Id = (*env)->GetFieldID(env, jni_arg36Class, "val", "I");
	jint jni_arg36 = (*env)->GetIntField(env, arg36, jni_arg36Id);
	for (jni_arg3i = 0 ; jni_arg3i < jni_arg3Size ; jni_arg3i++){
		if (jni_arg3Tmp[jni_arg3i] == JNI_FALSE){
			jni_arg3[jni_arg3i] = 0;
		} else {
			jni_arg3[jni_arg3i] = 1;
		}
	}

	sneupd_(&jni_arg1, jni_arg2, jni_arg3, jni_arg5, jni_arg7, jni_arg9, &arg11, &arg12, &arg13, jni_arg14, jni_arg16, &arg17, jni_arg18, &jni_arg19, &arg20, jni_arg21, &arg23, jni_arg24, &arg26, jni_arg27, jni_arg29, jni_arg31, jni_arg33, &arg35, &jni_arg36);

	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	for (jni_arg3i = 0 ; jni_arg3i < jni_arg3Size ; jni_arg3i++){
		if (jni_arg3[jni_arg3i] == 0){
			jni_arg3Tmp[jni_arg3i] = JNI_FALSE;
		} else {
			jni_arg3Tmp[jni_arg3i] = JNI_TRUE;
		}
	}
	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3Tmp, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg9, jni_arg9, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg14, jni_arg14, 0);
	(*env)->ReleaseStringUTFChars(env, arg16, jni_arg16);
	(*env)->ReleaseStringUTFChars(env, arg18, jni_arg18);
	(*env)->SetIntField(env, arg19, jni_arg19Id, jni_arg19);
	(*env)->ReleasePrimitiveArrayCritical(env, arg21, jni_arg21, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg24, jni_arg24, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg27, jni_arg27, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg29, jni_arg29, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg31, jni_arg31, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg33, jni_arg33, 0);
	(*env)->SetIntField(env, arg36, jni_arg36Id, jni_arg36);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_sngets (JNIEnv * env, jobject calling_obj, jint arg1, jstring arg2, jobject arg3, jobject arg4, jfloatArray arg5, jfloatArray arg7, jfloatArray arg9, jfloatArray arg11, jfloatArray arg13){
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jclass jni_arg3Class = (*env)->GetObjectClass(env, arg3);
	jfieldID jni_arg3Id = (*env)->GetFieldID(env, jni_arg3Class, "val", "I");
	jint jni_arg3 = (*env)->GetIntField(env, arg3, jni_arg3Id);
	jclass jni_arg4Class = (*env)->GetObjectClass(env, arg4);
	jfieldID jni_arg4Id = (*env)->GetFieldID(env, jni_arg4Class, "val", "I");
	jint jni_arg4 = (*env)->GetIntField(env, arg4, jni_arg4Id);
	jfloat * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);
	jfloat * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jfloat * jni_arg9 = (*env)->GetPrimitiveArrayCritical(env, arg9, JNI_FALSE);
	check_memory(env, jni_arg9);
	jfloat * jni_arg11 = (*env)->GetPrimitiveArrayCritical(env, arg11, JNI_FALSE);
	check_memory(env, jni_arg11);
	jfloat * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);

	sngets_(&arg1, jni_arg2, &jni_arg3, &jni_arg4, jni_arg5, jni_arg7, jni_arg9, jni_arg11, jni_arg13);

	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->SetIntField(env, arg3, jni_arg3Id, jni_arg3);
	(*env)->SetIntField(env, arg4, jni_arg4Id, jni_arg4);
	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg9, jni_arg9, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg11, jni_arg11, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_ssaitr (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jint arg4, jint arg5, jint arg6, jfloatArray arg7, jobject arg9, jfloatArray arg10, jint arg12, jfloatArray arg13, jint arg15, jintArray arg16, jfloatArray arg18, jobject arg20){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jfloat * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jclass jni_arg9Class = (*env)->GetObjectClass(env, arg9);
	jfieldID jni_arg9Id = (*env)->GetFieldID(env, jni_arg9Class, "val", "D");
	jfloat jni_arg9 = (*env)->GetFloatField(env, arg9, jni_arg9Id);
	jfloat * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jfloat * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);
	jint * jni_arg16 = (*env)->GetPrimitiveArrayCritical(env, arg16, JNI_FALSE);
	check_memory(env, jni_arg16);
	jfloat * jni_arg18 = (*env)->GetPrimitiveArrayCritical(env, arg18, JNI_FALSE);
	check_memory(env, jni_arg18);
	jclass jni_arg20Class = (*env)->GetObjectClass(env, arg20);
	jfieldID jni_arg20Id = (*env)->GetFieldID(env, jni_arg20Class, "val", "I");
	jint jni_arg20 = (*env)->GetIntField(env, arg20, jni_arg20Id);

	ssaitr_(&jni_arg1, jni_arg2, &arg3, &arg4, &arg5, &arg6, jni_arg7, &jni_arg9, jni_arg10, &arg12, jni_arg13, &arg15, jni_arg16, jni_arg18, &jni_arg20);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->SetFloatField(env, arg9, jni_arg9Id, jni_arg9);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg16, jni_arg16, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg18, jni_arg18, 0);
	(*env)->SetIntField(env, arg20, jni_arg20Id, jni_arg20);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_ssapps (JNIEnv * env, jobject calling_obj, jint arg1, jint arg2, jint arg3, jfloatArray arg4, jfloatArray arg6, jint arg8, jfloatArray arg9, jint arg11, jfloatArray arg12, jfloatArray arg14, jint arg16, jfloatArray arg17){
	jfloat * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jfloat * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jfloat * jni_arg9 = (*env)->GetPrimitiveArrayCritical(env, arg9, JNI_FALSE);
	check_memory(env, jni_arg9);
	jfloat * jni_arg12 = (*env)->GetPrimitiveArrayCritical(env, arg12, JNI_FALSE);
	check_memory(env, jni_arg12);
	jfloat * jni_arg14 = (*env)->GetPrimitiveArrayCritical(env, arg14, JNI_FALSE);
	check_memory(env, jni_arg14);
	jfloat * jni_arg17 = (*env)->GetPrimitiveArrayCritical(env, arg17, JNI_FALSE);
	check_memory(env, jni_arg17);

	ssapps_(&arg1, &arg2, &arg3, jni_arg4, jni_arg6, &arg8, jni_arg9, &arg11, jni_arg12, jni_arg14, &arg16, jni_arg17);

	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg9, jni_arg9, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg12, jni_arg12, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg14, jni_arg14, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg17, jni_arg17, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_ssaup2 (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jstring arg4, jobject arg5, jobject arg6, jfloat arg7, jfloatArray arg8, jint arg10, jint arg11, jint arg12, jobject arg13, jfloatArray arg14, jint arg16, jfloatArray arg17, jint arg19, jfloatArray arg20, jfloatArray arg22, jfloatArray arg24, jint arg26, jfloatArray arg27, jintArray arg29, jfloatArray arg31, jobject arg33){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	char * jni_arg4 = (char *)(*env)->GetStringUTFChars(env, arg4, JNI_FALSE);
	jclass jni_arg5Class = (*env)->GetObjectClass(env, arg5);
	jfieldID jni_arg5Id = (*env)->GetFieldID(env, jni_arg5Class, "val", "I");
	jint jni_arg5 = (*env)->GetIntField(env, arg5, jni_arg5Id);
	jclass jni_arg6Class = (*env)->GetObjectClass(env, arg6);
	jfieldID jni_arg6Id = (*env)->GetFieldID(env, jni_arg6Class, "val", "I");
	jint jni_arg6 = (*env)->GetIntField(env, arg6, jni_arg6Id);
	jfloat * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jclass jni_arg13Class = (*env)->GetObjectClass(env, arg13);
	jfieldID jni_arg13Id = (*env)->GetFieldID(env, jni_arg13Class, "val", "I");
	jint jni_arg13 = (*env)->GetIntField(env, arg13, jni_arg13Id);
	jfloat * jni_arg14 = (*env)->GetPrimitiveArrayCritical(env, arg14, JNI_FALSE);
	check_memory(env, jni_arg14);
	jfloat * jni_arg17 = (*env)->GetPrimitiveArrayCritical(env, arg17, JNI_FALSE);
	check_memory(env, jni_arg17);
	jfloat * jni_arg20 = (*env)->GetPrimitiveArrayCritical(env, arg20, JNI_FALSE);
	check_memory(env, jni_arg20);
	jfloat * jni_arg22 = (*env)->GetPrimitiveArrayCritical(env, arg22, JNI_FALSE);
	check_memory(env, jni_arg22);
	jfloat * jni_arg24 = (*env)->GetPrimitiveArrayCritical(env, arg24, JNI_FALSE);
	check_memory(env, jni_arg24);
	jfloat * jni_arg27 = (*env)->GetPrimitiveArrayCritical(env, arg27, JNI_FALSE);
	check_memory(env, jni_arg27);
	jint * jni_arg29 = (*env)->GetPrimitiveArrayCritical(env, arg29, JNI_FALSE);
	check_memory(env, jni_arg29);
	jfloat * jni_arg31 = (*env)->GetPrimitiveArrayCritical(env, arg31, JNI_FALSE);
	check_memory(env, jni_arg31);
	jclass jni_arg33Class = (*env)->GetObjectClass(env, arg33);
	jfieldID jni_arg33Id = (*env)->GetFieldID(env, jni_arg33Class, "val", "I");
	jint jni_arg33 = (*env)->GetIntField(env, arg33, jni_arg33Id);

	ssaup2_(&jni_arg1, jni_arg2, &arg3, jni_arg4, &jni_arg5, &jni_arg6, &arg7, jni_arg8, &arg10, &arg11, &arg12, &jni_arg13, jni_arg14, &arg16, jni_arg17, &arg19, jni_arg20, jni_arg22, jni_arg24, &arg26, jni_arg27, jni_arg29, jni_arg31, &jni_arg33);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleaseStringUTFChars(env, arg4, jni_arg4);
	(*env)->SetIntField(env, arg5, jni_arg5Id, jni_arg5);
	(*env)->SetIntField(env, arg6, jni_arg6Id, jni_arg6);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->SetIntField(env, arg13, jni_arg13Id, jni_arg13);
	(*env)->ReleasePrimitiveArrayCritical(env, arg14, jni_arg14, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg17, jni_arg17, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg20, jni_arg20, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg22, jni_arg22, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg24, jni_arg24, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg27, jni_arg27, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg29, jni_arg29, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg31, jni_arg31, 0);
	(*env)->SetIntField(env, arg33, jni_arg33Id, jni_arg33);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_ssaupd (JNIEnv * env, jobject calling_obj, jobject arg1, jstring arg2, jint arg3, jstring arg4, jint arg5, jobject arg6, jfloatArray arg7, jint arg9, jfloatArray arg10, jint arg12, jintArray arg13, jintArray arg15, jfloatArray arg17, jfloatArray arg19, jint arg21, jobject arg22){
	jclass jni_arg1Class = (*env)->GetObjectClass(env, arg1);
	jfieldID jni_arg1Id = (*env)->GetFieldID(env, jni_arg1Class, "val", "I");
	jint jni_arg1 = (*env)->GetIntField(env, arg1, jni_arg1Id);
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	char * jni_arg4 = (char *)(*env)->GetStringUTFChars(env, arg4, JNI_FALSE);
	jclass jni_arg6Class = (*env)->GetObjectClass(env, arg6);
	jfieldID jni_arg6Id = (*env)->GetFieldID(env, jni_arg6Class, "val", "D");
	jfloat jni_arg6 = (*env)->GetFloatField(env, arg6, jni_arg6Id);
	jfloat * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jfloat * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jint * jni_arg13 = (*env)->GetPrimitiveArrayCritical(env, arg13, JNI_FALSE);
	check_memory(env, jni_arg13);
	jint * jni_arg15 = (*env)->GetPrimitiveArrayCritical(env, arg15, JNI_FALSE);
	check_memory(env, jni_arg15);
	jfloat * jni_arg17 = (*env)->GetPrimitiveArrayCritical(env, arg17, JNI_FALSE);
	check_memory(env, jni_arg17);
	jfloat * jni_arg19 = (*env)->GetPrimitiveArrayCritical(env, arg19, JNI_FALSE);
	check_memory(env, jni_arg19);
	jclass jni_arg22Class = (*env)->GetObjectClass(env, arg22);
	jfieldID jni_arg22Id = (*env)->GetFieldID(env, jni_arg22Class, "val", "I");
	jint jni_arg22 = (*env)->GetIntField(env, arg22, jni_arg22Id);

	ssaupd_(&jni_arg1, jni_arg2, &arg3, jni_arg4, &arg5, &jni_arg6, jni_arg7, &arg9, jni_arg10, &arg12, jni_arg13, jni_arg15, jni_arg17, jni_arg19, &arg21, &jni_arg22);

	(*env)->SetIntField(env, arg1, jni_arg1Id, jni_arg1);
	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->ReleaseStringUTFChars(env, arg4, jni_arg4);
	(*env)->SetFloatField(env, arg6, jni_arg6Id, jni_arg6);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg13, jni_arg13, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg15, jni_arg15, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg17, jni_arg17, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg19, jni_arg19, 0);
	(*env)->SetIntField(env, arg22, jni_arg22Id, jni_arg22);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_ssconv (JNIEnv * env, jobject calling_obj, jint arg1, jfloatArray arg2, jfloatArray arg4, jfloat arg6, jobject arg7){
	jfloat * jni_arg2 = (*env)->GetPrimitiveArrayCritical(env, arg2, JNI_FALSE);
	check_memory(env, jni_arg2);
	jfloat * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jclass jni_arg7Class = (*env)->GetObjectClass(env, arg7);
	jfieldID jni_arg7Id = (*env)->GetFieldID(env, jni_arg7Class, "val", "I");
	jint jni_arg7 = (*env)->GetIntField(env, arg7, jni_arg7Id);

	ssconv_(&arg1, jni_arg2, jni_arg4, &arg6, &jni_arg7);

	(*env)->ReleasePrimitiveArrayCritical(env, arg2, jni_arg2, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->SetIntField(env, arg7, jni_arg7Id, jni_arg7);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_sseigt (JNIEnv * env, jobject calling_obj, jfloat arg1, jint arg2, jfloatArray arg3, jint arg5, jfloatArray arg6, jfloatArray arg8, jfloatArray arg10, jobject arg12){
	jfloat * jni_arg3 = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	check_memory(env, jni_arg3);
	jfloat * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jfloat * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jfloat * jni_arg10 = (*env)->GetPrimitiveArrayCritical(env, arg10, JNI_FALSE);
	check_memory(env, jni_arg10);
	jclass jni_arg12Class = (*env)->GetObjectClass(env, arg12);
	jfieldID jni_arg12Id = (*env)->GetFieldID(env, jni_arg12Class, "val", "I");
	jint jni_arg12 = (*env)->GetIntField(env, arg12, jni_arg12Id);

	sseigt_(&arg1, &arg2, jni_arg3, &arg5, jni_arg6, jni_arg8, jni_arg10, &jni_arg12);

	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg10, jni_arg10, 0);
	(*env)->SetIntField(env, arg12, jni_arg12Id, jni_arg12);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_ssesrt (JNIEnv * env, jobject calling_obj, jstring arg1, jboolean arg2, jint arg3, jfloatArray arg4, jint arg6, jfloatArray arg7, jint arg9){
	char * jni_arg1 = (char *)(*env)->GetStringUTFChars(env, arg1, JNI_FALSE);
	logical jni_arg2 = (logical)arg2;
	jfloat * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jfloat * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);

	ssesrt_(jni_arg1, &jni_arg2, &arg3, jni_arg4, &arg6, jni_arg7, &arg9);

	(*env)->ReleaseStringUTFChars(env, arg1, jni_arg1);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_sseupd (JNIEnv * env, jobject calling_obj, jboolean arg1, jstring arg2, jbooleanArray arg3, jfloatArray arg5, jfloatArray arg7, jint arg9, jfloat arg10, jstring arg11, jint arg12, jstring arg13, jobject arg14, jfloat arg15, jfloatArray arg16, jint arg18, jfloatArray arg19, jint arg21, jintArray arg22, jintArray arg24, jfloatArray arg26, jfloatArray arg28, jint arg30, jobject arg31){
	logical jni_arg1 = (logical)arg1;
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jboolean * jni_arg3Tmp = (*env)->GetPrimitiveArrayCritical(env, arg3, JNI_FALSE);
	jint jni_arg3Size = (*env)->GetArrayLength(env, arg3);
	logical jni_arg3[jni_arg3Size];
	int jni_arg3i;
	jfloat * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);
	jfloat * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	char * jni_arg11 = (char *)(*env)->GetStringUTFChars(env, arg11, JNI_FALSE);
	char * jni_arg13 = (char *)(*env)->GetStringUTFChars(env, arg13, JNI_FALSE);
	jclass jni_arg14Class = (*env)->GetObjectClass(env, arg14);
	jfieldID jni_arg14Id = (*env)->GetFieldID(env, jni_arg14Class, "val", "I");
	jint jni_arg14 = (*env)->GetIntField(env, arg14, jni_arg14Id);
	jfloat * jni_arg16 = (*env)->GetPrimitiveArrayCritical(env, arg16, JNI_FALSE);
	check_memory(env, jni_arg16);
	jfloat * jni_arg19 = (*env)->GetPrimitiveArrayCritical(env, arg19, JNI_FALSE);
	check_memory(env, jni_arg19);
	jint * jni_arg22 = (*env)->GetPrimitiveArrayCritical(env, arg22, JNI_FALSE);
	check_memory(env, jni_arg22);
	jint * jni_arg24 = (*env)->GetPrimitiveArrayCritical(env, arg24, JNI_FALSE);
	check_memory(env, jni_arg24);
	jfloat * jni_arg26 = (*env)->GetPrimitiveArrayCritical(env, arg26, JNI_FALSE);
	check_memory(env, jni_arg26);
	jfloat * jni_arg28 = (*env)->GetPrimitiveArrayCritical(env, arg28, JNI_FALSE);
	check_memory(env, jni_arg28);
	jclass jni_arg31Class = (*env)->GetObjectClass(env, arg31);
	jfieldID jni_arg31Id = (*env)->GetFieldID(env, jni_arg31Class, "val", "I");
	jint jni_arg31 = (*env)->GetIntField(env, arg31, jni_arg31Id);
	for (jni_arg3i = 0 ; jni_arg3i < jni_arg3Size ; jni_arg3i++){
		if (jni_arg3Tmp[jni_arg3i] == JNI_FALSE){
			jni_arg3[jni_arg3i] = 0;
		} else {
			jni_arg3[jni_arg3i] = 1;
		}
	}

	sseupd_(&jni_arg1, jni_arg2, jni_arg3, jni_arg5, jni_arg7, &arg9, &arg10, jni_arg11, &arg12, jni_arg13, &jni_arg14, &arg15, jni_arg16, &arg18, jni_arg19, &arg21, jni_arg22, jni_arg24, jni_arg26, jni_arg28, &arg30, &jni_arg31);

	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	for (jni_arg3i = 0 ; jni_arg3i < jni_arg3Size ; jni_arg3i++){
		if (jni_arg3[jni_arg3i] == 0){
			jni_arg3Tmp[jni_arg3i] = JNI_FALSE;
		} else {
			jni_arg3Tmp[jni_arg3i] = JNI_TRUE;
		}
	}
	(*env)->ReleasePrimitiveArrayCritical(env, arg3, jni_arg3Tmp, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleaseStringUTFChars(env, arg11, jni_arg11);
	(*env)->ReleaseStringUTFChars(env, arg13, jni_arg13);
	(*env)->SetIntField(env, arg14, jni_arg14Id, jni_arg14);
	(*env)->ReleasePrimitiveArrayCritical(env, arg16, jni_arg16, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg19, jni_arg19, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg22, jni_arg22, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg24, jni_arg24, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg26, jni_arg26, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg28, jni_arg28, 0);
	(*env)->SetIntField(env, arg31, jni_arg31Id, jni_arg31);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_ssgets (JNIEnv * env, jobject calling_obj, jint arg1, jstring arg2, jobject arg3, jobject arg4, jfloatArray arg5, jfloatArray arg7, jfloatArray arg9){
	char * jni_arg2 = (char *)(*env)->GetStringUTFChars(env, arg2, JNI_FALSE);
	jclass jni_arg3Class = (*env)->GetObjectClass(env, arg3);
	jfieldID jni_arg3Id = (*env)->GetFieldID(env, jni_arg3Class, "val", "I");
	jint jni_arg3 = (*env)->GetIntField(env, arg3, jni_arg3Id);
	jclass jni_arg4Class = (*env)->GetObjectClass(env, arg4);
	jfieldID jni_arg4Id = (*env)->GetFieldID(env, jni_arg4Class, "val", "I");
	jint jni_arg4 = (*env)->GetIntField(env, arg4, jni_arg4Id);
	jfloat * jni_arg5 = (*env)->GetPrimitiveArrayCritical(env, arg5, JNI_FALSE);
	check_memory(env, jni_arg5);
	jfloat * jni_arg7 = (*env)->GetPrimitiveArrayCritical(env, arg7, JNI_FALSE);
	check_memory(env, jni_arg7);
	jfloat * jni_arg9 = (*env)->GetPrimitiveArrayCritical(env, arg9, JNI_FALSE);
	check_memory(env, jni_arg9);

	ssgets_(&arg1, jni_arg2, &jni_arg3, &jni_arg4, jni_arg5, jni_arg7, jni_arg9);

	(*env)->ReleaseStringUTFChars(env, arg2, jni_arg2);
	(*env)->SetIntField(env, arg3, jni_arg3Id, jni_arg3);
	(*env)->SetIntField(env, arg4, jni_arg4Id, jni_arg4);
	(*env)->ReleasePrimitiveArrayCritical(env, arg5, jni_arg5, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg7, jni_arg7, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg9, jni_arg9, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_ssortc (JNIEnv * env, jobject calling_obj, jstring arg1, jboolean arg2, jint arg3, jfloatArray arg4, jfloatArray arg6, jfloatArray arg8){
	char * jni_arg1 = (char *)(*env)->GetStringUTFChars(env, arg1, JNI_FALSE);
	logical jni_arg2 = (logical)arg2;
	jfloat * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jfloat * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jfloat * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);

	ssortc_(jni_arg1, &jni_arg2, &arg3, jni_arg4, jni_arg6, jni_arg8);

	(*env)->ReleaseStringUTFChars(env, arg1, jni_arg1);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_ssortr (JNIEnv * env, jobject calling_obj, jstring arg1, jboolean arg2, jint arg3, jfloatArray arg4, jfloatArray arg6){
	char * jni_arg1 = (char *)(*env)->GetStringUTFChars(env, arg1, JNI_FALSE);
	logical jni_arg2 = (logical)arg2;
	jfloat * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jfloat * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);

	ssortr_(jni_arg1, &jni_arg2, &arg3, jni_arg4, jni_arg6);

	(*env)->ReleaseStringUTFChars(env, arg1, jni_arg1);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_sstatn (JNIEnv * env, jobject calling_obj){

	sstatn_();

}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_sstats (JNIEnv * env, jobject calling_obj){

	sstats_();

}

JNIEXPORT void JNICALL Java_org_netlib_arpack_NativeARPACK_sstqrb (JNIEnv * env, jobject calling_obj, jint arg1, jfloatArray arg2, jfloatArray arg4, jfloatArray arg6, jfloatArray arg8, jobject arg10){
	jfloat * jni_arg2 = (*env)->GetPrimitiveArrayCritical(env, arg2, JNI_FALSE);
	check_memory(env, jni_arg2);
	jfloat * jni_arg4 = (*env)->GetPrimitiveArrayCritical(env, arg4, JNI_FALSE);
	check_memory(env, jni_arg4);
	jfloat * jni_arg6 = (*env)->GetPrimitiveArrayCritical(env, arg6, JNI_FALSE);
	check_memory(env, jni_arg6);
	jfloat * jni_arg8 = (*env)->GetPrimitiveArrayCritical(env, arg8, JNI_FALSE);
	check_memory(env, jni_arg8);
	jclass jni_arg10Class = (*env)->GetObjectClass(env, arg10);
	jfieldID jni_arg10Id = (*env)->GetFieldID(env, jni_arg10Class, "val", "I");
	jint jni_arg10 = (*env)->GetIntField(env, arg10, jni_arg10Id);

	sstqrb_(&arg1, jni_arg2, jni_arg4, jni_arg6, jni_arg8, &jni_arg10);

	(*env)->ReleasePrimitiveArrayCritical(env, arg2, jni_arg2, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg4, jni_arg4, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg6, jni_arg6, 0);
	(*env)->ReleasePrimitiveArrayCritical(env, arg8, jni_arg8, 0);
	(*env)->SetIntField(env, arg10, jni_arg10Id, jni_arg10);
}

